wandb_version: 1

test_size:
  desc: null
  value: 0.2
val_size:
  desc: null
  value: 0.2
random_state:
  desc: null
  value: 3
target_var_name:
  desc: null
  value: poisonous
features:
  desc: null
  value:
  - cap-shape
  - cap-surface
  - cap-color
  - bruises
  - odor
  - gill-attachment
  - gill-spacing
  - gill-size
  - gill-color
  - stalk-shape
  - stalk-surface-above-ring
  - stalk-surface-below-ring
  - stalk-color-above-ring
  - stalk-color-below-ring
  - veil-type
  - veil-color
  - ring-number
  - ring-type
  - spore-print-color
  - population
  - habitat
kernel:
  desc: null
  value: poly
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699192119.305663
    t:
      1:
      - 5
      - 53
      - 55
      - 105
      2:
      - 5
      - 53
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
    viz:
      confusion_matrix:
        id: wandb/confusion_matrix/v1
        historyFieldSettings:
          x-axis: _step
          key: confusion_matrix
